# DOCKER_BUILDKIT=1 docker build -t benjamintanweihao/alpr-metadata env -f env/docker/Dockerfile.metadata
# DOCKER_BUILDKIT=1 docker build --no-cache -t benjamintanweihao/alpr-metadata env -f env/docker/Dockerfile.metadata

FROM python:3.7-slim-buster
RUN pip3 install kubeflow.metadata